# Generated by Django 2.0.2 on 2018-08-09 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ObjectId', models.CharField(blank=True, max_length=40)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clubs_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ObjectId', models.CharField(blank=True, max_length=40)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ObjectId', models.CharField(blank=True, max_length=40)),
                ('Comments', models.TextField()),
                ('ThoughtId', models.CharField(max_length=35)),
                ('Username', models.CharField(max_length=50)),
                ('ReplyCount', models.IntegerField(default=0)),
                ('Symbol', models.CharField(blank=True, max_length=15)),
                ('Verify', models.CharField(max_length=6)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ObjectId', models.CharField(blank=True, max_length=40)),
                ('EventName', models.CharField(blank=True, max_length=50)),
                ('EventImage', models.FileField(upload_to='EventImages/', verbose_name='ImageFile')),
                ('Venue', models.CharField(blank=True, max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(blank=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replies_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ObjectId', models.CharField(blank=True, max_length=40)),
                ('Reply', models.TextField()),
                ('Username', models.CharField(max_length=50)),
                ('Symbol', models.CharField(blank=True, max_length=15)),
                ('CommentId', models.CharField(max_length=35)),
                ('ThoughtId', models.CharField(max_length=35)),
                ('Verified', models.CharField(max_length=6)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialMsg_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ObjectId', models.CharField(blank=True, max_length=40)),
                ('SpecialMsg', models.FileField(upload_to='SpecialMsg/')),
                ('Duration', models.IntegerField()),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thoughts_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ObjectId', models.CharField(blank=True, max_length=40)),
                ('Thoughts', models.TextField()),
                ('Backgrounds', models.CharField(max_length=50)),
                ('Likes', models.IntegerField(default=0)),
                ('Dislikes', models.IntegerField(default=0)),
                ('User', models.CharField(max_length=100)),
                ('Likeslist', models.TextField(blank=True)),
                ('Dislikeslist', models.TextField(blank=True)),
                ('Symbols', models.TextField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Trendno', models.IntegerField(default=0)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
