# Generated by Django 2.0.2 on 2018-08-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yochans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication_db',
            name='ObjectId',
        ),
        migrations.RemoveField(
            model_name='clubs_db',
            name='ObjectId',
        ),
        migrations.RemoveField(
            model_name='events_db',
            name='ObjectId',
        ),
        migrations.RemoveField(
            model_name='specialmsg_db',
            name='ObjectId',
        ),
    ]
