# Generated by Django 2.0.2 on 2018-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yochans', '0003_auto_20180809_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_db',
            name='ObjectId',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
