# Generated by Django 2.0.2 on 2018-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yochans', '0006_auto_20180813_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_db',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
    ]
