# Generated by Django 2.0.2 on 2018-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yochans', '0009_auto_20180822_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_db',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
