# Generated by Django 2.0.2 on 2018-08-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yochans', '0010_auto_20180822_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughts_db',
            name='Recom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events_db',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
