# Generated by Django 2.0.2 on 2018-09-06 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Yochans', '0011_auto_20180831_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=40)),
                ('Title', models.TextField()),
                ('URL', models.TextField()),
                ('Author', models.CharField(max_length=50)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
