# Generated by Django 2.0.2 on 2018-09-10 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Yochans', '0012_blogs_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Archive_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CommentId', models.CharField(max_length=40)),
                ('Comments', models.TextField()),
                ('ThoughtId', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=50)),
                ('ReplyCount', models.IntegerField(default=0)),
                ('Symbol', models.CharField(blank=True, max_length=15)),
                ('Verify', models.CharField(max_length=6)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replies_Archive_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ReplyId', models.CharField(max_length=40)),
                ('Reply', models.TextField()),
                ('Username', models.CharField(max_length=50)),
                ('Symbol', models.CharField(blank=True, max_length=15)),
                ('CommentId', models.CharField(max_length=40)),
                ('ThoughtId', models.CharField(max_length=40)),
                ('Verified', models.CharField(max_length=6)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thoughts_Archive_db',
            fields=[
                ('PrimeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ThougthId', models.CharField(max_length=40)),
                ('Thoughts', models.TextField()),
                ('Backgrounds', models.CharField(max_length=50)),
                ('Likes', models.IntegerField(default=0)),
                ('Dislikes', models.IntegerField(default=0)),
                ('User', models.CharField(max_length=50)),
                ('Likeslist', models.TextField(blank=True)),
                ('Dislikeslist', models.TextField(blank=True)),
                ('Anonymous', models.CharField(max_length=8)),
                ('Recom', models.IntegerField(default=0)),
                ('Trendno', models.IntegerField(default=0)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
