# Generated by Django 2.0.2 on 2018-09-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yochans', '0013_comments_archive_db_replies_archive_db_thoughts_archive_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoughts_archive_db',
            old_name='ThougthId',
            new_name='ThoughtId',
        ),
    ]
